-- Lerd launcher. Generated by lerd install; edits here are overwritten.
--
-- Clicking the icon has to bring the environment up, and a start takes the
-- better part of a minute, so this draws a splash while it runs: lerd's mark,
-- what is happening, and how far along it is. Progress comes from the daemon's
-- own start stream when it is reachable, and falls back to a plain `lerd start`
-- when it is not.

use framework "Foundation"
use framework "AppKit"
use scripting additions

property daemonURL : "http://127.0.0.1:7073"
property vhostURL : "http://lerd.localhost"
property feedPath : "/tmp/lerd-launcher-feed"
-- Filled in at install time with the binary this install resolved to, so a
-- Homebrew keg outside the candidate list below still works.
property installedBin : "{{LERD_BIN}}"

-- The splash, held here so the update helpers can reach it. All three stay
-- missing value when the window could not be built, which is the signal to
-- fall back to the system progress bar rather than run blind.
property splashWindow : missing value
property splashStep : missing value
property splashBar : missing value

on run
	set lerdBin to my findLerd()
	if lerdBin is "" then
		do shell script "open https://lerd.sh/getting-started/installation/"
		return
	end if
	if my serving(vhostURL & "/?lerd-probe=1") then
		my openDashboard(lerdBin)
		return
	end if

	my openSplash()
	set streamed to my beginStart(lerdBin)

	-- Wait for the start to report itself finished, not merely for nginx to
	-- answer: the vhost comes up well before the databases behind it, and a
	-- dashboard opened at that moment shows sites returning 500.
	repeat 300 times
		my wait(1)
		if streamed then
			my showProgress()
			if my startFinished() then exit repeat
		else
			if my serving(vhostURL & "/?lerd-probe=1") then exit repeat
		end if
	end repeat

	my setStep("Opening the dashboard")
	my openDashboard(lerdBin)
	my closeSplash()
end run

-- openSplash draws a borderless window with the mark, a caption and a bar. Any
-- failure leaves the properties unset and the system progress bar takes over,
-- so a launcher that cannot draw still reports what it is doing.
on openSplash()
	try
		set winW to 380
		set winH to 190
		set nsApp to current application's NSApplication's sharedApplication()
		nsApp's setActivationPolicy:(current application's NSApplicationActivationPolicyRegular)

		set win to current application's NSWindow's alloc()'s initWithContentRect:{{0, 0}, {winW, winH}} styleMask:(current application's NSWindowStyleMaskBorderless) backing:(current application's NSBackingStoreBuffered) defer:false
		win's setOpaque:false
		win's setHasShadow:true
		win's setLevel:(current application's NSFloatingWindowLevel)
		win's setBackgroundColor:(current application's NSColor's clearColor())

		-- A visual effect view draws its own material, so the panel does not
		-- depend on a layer background colour taking effect.
		set canvas to current application's NSVisualEffectView's alloc()'s initWithFrame:{{0, 0}, {winW, winH}}
		canvas's setMaterial:(current application's NSVisualEffectMaterialPopover)
		canvas's setBlendingMode:(current application's NSVisualEffectBlendingModeBehindWindow)
		canvas's setState:(current application's NSVisualEffectStateActive)
		canvas's setWantsLayer:true
		canvas's layer()'s setCornerRadius:16
		canvas's layer()'s setMasksToBounds:true
		win's setContentView:canvas

		set iconFile to (POSIX path of (path to me)) & "Contents/Resources/lerd-mark.png"
		set mark to current application's NSImage's alloc()'s initWithContentsOfFile:iconFile
		set markView to current application's NSImageView's alloc()'s initWithFrame:{{(winW - 64) / 2, winH - 86}, {64, 64}}
		markView's setImage:mark
		canvas's addSubview:markView

		set titleField to my caption(0, winH - 116, winW, 22, "Starting Lerd", 15, true)
		set stepField to my caption(0, winH - 138, winW, 18, "Preparing the environment", 11, false)
		canvas's addSubview:titleField
		canvas's addSubview:stepField

		set bar to current application's NSProgressIndicator's alloc()'s initWithFrame:{{26, 34}, {winW - 52, 8}}
		bar's setStyle:(current application's NSProgressIndicatorStyleBar)
		bar's setIndeterminate:true
		bar's startAnimation:(missing value)
		canvas's addSubview:bar

		win's |center|()
		win's makeKeyAndOrderFront:(missing value)
		nsApp's activateIgnoringOtherApps:true

		set splashWindow to win
		set splashStep to stepField
		set splashBar to bar
	on error
		set splashWindow to missing value
		set progress description to "Starting Lerd"
		set progress additional description to "Preparing the environment"
		set progress total steps to -1
		set progress completed steps to 0
	end try
end openSplash

on closeSplash()
	if splashWindow is missing value then return
	try
		splashWindow's orderOut:(missing value)
	end try
end closeSplash

on caption(x, y, w, h, txt, sz, isBold)
	set f to current application's NSTextField's alloc()'s initWithFrame:{{x, y}, {w, h}}
	f's setStringValue:txt
	f's setBezeled:false
	f's setDrawsBackground:false
	f's setEditable:false
	f's setSelectable:false
	f's setAlignment:(current application's NSTextAlignmentCenter)
	if isBold then
		f's setFont:(current application's NSFont's boldSystemFontOfSize:sz)
	else
		f's setFont:(current application's NSFont's systemFontOfSize:sz)
		f's setTextColor:(current application's NSColor's secondaryLabelColor())
	end if
	return f
end caption

-- wait yields to the run loop rather than sleeping. A plain delay would block
-- the main thread, and the window would never redraw.
on wait(secs)
	if splashWindow is missing value then
		delay secs
		return
	end if
	current application's NSRunLoop's mainRunLoop()'s runUntilDate:(current application's NSDate's dateWithTimeIntervalSinceNow:(secs as real))
end wait

on setStep(txt)
	if splashWindow is missing value then
		set progress additional description to txt
	else
		splashStep's setStringValue:txt
	end if
end setStep

-- beginStart kicks the start off and reports whether its progress is readable.
-- The daemon streams one line per unit; `lerd start` writes nothing until it is
-- finished, so that path keeps the indeterminate bar rather than fake a count.
on beginStart(lerdBin)
	if my serving(daemonURL & "/api/status") then
		do shell script "rm -f " & quoted form of feedPath & "; curl -sN -X POST -H 'X-Lerd-CSRF: 1' " & quoted form of (daemonURL & "/api/lerd/start") & " > " & quoted form of feedPath & " 2>/dev/null &"
		return true
	end if
	do shell script quoted form of lerdBin & " start > /dev/null 2>&1 &"
	return false
end beginStart

on startFinished()
	try
		do shell script "grep -q '\"phase\":\"done\"' " & quoted form of feedPath & " || grep -q '\"phase\":\"failed\"' " & quoted form of feedPath
		return true
	on error
		return false
	end try
end startFinished

on showProgress()
	set unitTotal to 0
	set unitsDone to 0
	try
		set unitTotal to (do shell script "grep -o '\"total\":[0-9]*' " & quoted form of feedPath & " | tail -1 | cut -d: -f2") as integer
	end try
	try
		set unitsDone to (do shell script "grep -c '\"phase\":\"unit\"' " & quoted form of feedPath) as integer
	end try
	try
		set unitName to (do shell script "grep -o '\"unit\":\"[^\"]*\"' " & quoted form of feedPath & " | tail -1 | cut -d'\"' -f4")
		if unitName is not "" then my setStep(unitName)
	end try
	if unitTotal is 0 then return
	if splashWindow is missing value then
		set progress total steps to unitTotal
		set progress completed steps to unitsDone
	else
		splashBar's setIndeterminate:false
		splashBar's setMaxValue:unitTotal
		splashBar's setDoubleValue:unitsDone
	end if
end showProgress

-- Finder starts this with launchd's bare PATH, so the binary is named outright
-- rather than looked up in a login shell's environment.
on findLerd()
	try
		return (do shell script "for c in " & quoted form of installedBin & " \"$HOME/.local/bin/lerd\" /opt/homebrew/bin/lerd /usr/local/bin/lerd; do if [ -x \"$c\" ]; then echo \"$c\"; break; fi; done")
	on error
		return ""
	end try
end findLerd

on serving(someURL)
	try
		do shell script "curl -fsS --max-time 2 -o /dev/null " & quoted form of someURL
		return true
	on error
		return false
	end try
end serving

on openDashboard(lerdBin)
	do shell script quoted form of lerdBin & " dashboard > /dev/null 2>&1 &"
end openDashboard
